# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/davi/Documentos/projeto-LP1-IMD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/davi/Documentos/projeto-LP1-IMD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davi/Documentos/projeto-LP1-IMD/CMakeFiles /home/davi/Documentos/projeto-LP1-IMD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davi/Documentos/projeto-LP1-IMD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/caixaSupermercado.o: src/caixaSupermercado.cpp.o
.PHONY : src/caixaSupermercado.o

# target to build an object file
src/caixaSupermercado.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/caixaSupermercado.cpp.o
.PHONY : src/caixaSupermercado.cpp.o

src/caixaSupermercado.i: src/caixaSupermercado.cpp.i
.PHONY : src/caixaSupermercado.i

# target to preprocess a source file
src/caixaSupermercado.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/caixaSupermercado.cpp.i
.PHONY : src/caixaSupermercado.cpp.i

src/caixaSupermercado.s: src/caixaSupermercado.cpp.s
.PHONY : src/caixaSupermercado.s

# target to generate assembly for a file
src/caixaSupermercado.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/caixaSupermercado.cpp.s
.PHONY : src/caixaSupermercado.cpp.s

src/carrinho.o: src/carrinho.cpp.o
.PHONY : src/carrinho.o

# target to build an object file
src/carrinho.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/carrinho.cpp.o
.PHONY : src/carrinho.cpp.o

src/carrinho.i: src/carrinho.cpp.i
.PHONY : src/carrinho.i

# target to preprocess a source file
src/carrinho.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/carrinho.cpp.i
.PHONY : src/carrinho.cpp.i

src/carrinho.s: src/carrinho.cpp.s
.PHONY : src/carrinho.s

# target to generate assembly for a file
src/carrinho.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/carrinho.cpp.s
.PHONY : src/carrinho.cpp.s

src/cliente.o: src/cliente.cpp.o
.PHONY : src/cliente.o

# target to build an object file
src/cliente.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/cliente.cpp.o
.PHONY : src/cliente.cpp.o

src/cliente.i: src/cliente.cpp.i
.PHONY : src/cliente.i

# target to preprocess a source file
src/cliente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/cliente.cpp.i
.PHONY : src/cliente.cpp.i

src/cliente.s: src/cliente.cpp.s
.PHONY : src/cliente.s

# target to generate assembly for a file
src/cliente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/cliente.cpp.s
.PHONY : src/cliente.cpp.s

src/endereco.o: src/endereco.cpp.o
.PHONY : src/endereco.o

# target to build an object file
src/endereco.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/endereco.cpp.o
.PHONY : src/endereco.cpp.o

src/endereco.i: src/endereco.cpp.i
.PHONY : src/endereco.i

# target to preprocess a source file
src/endereco.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/endereco.cpp.i
.PHONY : src/endereco.cpp.i

src/endereco.s: src/endereco.cpp.s
.PHONY : src/endereco.s

# target to generate assembly for a file
src/endereco.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/endereco.cpp.s
.PHONY : src/endereco.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/produto.o: src/produto.cpp.o
.PHONY : src/produto.o

# target to build an object file
src/produto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/produto.cpp.o
.PHONY : src/produto.cpp.o

src/produto.i: src/produto.cpp.i
.PHONY : src/produto.i

# target to preprocess a source file
src/produto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/produto.cpp.i
.PHONY : src/produto.cpp.i

src/produto.s: src/produto.cpp.s
.PHONY : src/produto.s

# target to generate assembly for a file
src/produto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/produto.cpp.s
.PHONY : src/produto.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/caixaSupermercado.o"
	@echo "... src/caixaSupermercado.i"
	@echo "... src/caixaSupermercado.s"
	@echo "... src/carrinho.o"
	@echo "... src/carrinho.i"
	@echo "... src/carrinho.s"
	@echo "... src/cliente.o"
	@echo "... src/cliente.i"
	@echo "... src/cliente.s"
	@echo "... src/endereco.o"
	@echo "... src/endereco.i"
	@echo "... src/endereco.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/produto.o"
	@echo "... src/produto.i"
	@echo "... src/produto.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

